parser: babel-eslint
rules:
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  es6: true
  node: true
extends: 'eslint:recommended'
