rules:
  no-underscore-dangle:
    - off
  padded-blocks:
    - error
    - classes: never
  no-use-before-define:
    - off
  import/no-extraneous-dependencies:
    - off
  import/no-unresolved:
    - off
  import/extensions:
    - off
parserOptions:
  ecmaVersion: 6
  sourceType: module
parser: typescript-eslint-parser
env:
  es6: true
  node: true
extends: 'airbnb-base'
